# Generated by Django 4.2.4 on 2023-08-30 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0004_alter_contact_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_script',
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
